export enum RFQStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  ASSIGNED = 'ASSIGNED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  NEGOTIATION = 'NEGOTIATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  CONVERTED = 'CONVERTED'
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum EntityType {
  RFQ = 'RFQ',
  QUOTATION = 'QUOTATION',
  ORDER = 'ORDER',
  PRODUCT = 'PRODUCT',
  SERVICE_BOOKING = 'SERVICE_BOOKING'
}
